version: '3'
services:

  phpadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_USER=bn_opencart
    ports:
      - '8888:80'
    logging:
      driver: none
    networks:
      - selenoid

  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    ports:
      - '3306:3306'
    logging:
      driver: none
    networks:
      - selenoid

  opencart:
    image: docker.io/bitnami/opencart:3
    ports:
      - '8082:8080'
      - '443:8443'
    environment:
      - OPENCART_HOST=192.168.177.208:8082
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'opencart_data:/bitnami/opencart'
      - 'opencart_storage_data:/bitnami/opencart_storage/'
    depends_on:
      - mariadb
    logging:
      driver: none
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:8080/index.php?route=account/register" ]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - selenoid

  tests:
    build: .
    depends_on:
      opencart:
        condition: service_healthy
    networks:
      - selenoid

volumes:
  mariadb_data:
    driver: local
  opencart_data:
    driver: local
  opencart_storage_data:
    driver: local

networks:
  selenoid:
    driver: bridge